[tool.poetry]
name = "dracoon"
version = "1.10.0"
description = "DRACOON API wrapper in Python"
authors = ["Octavio Simone <o.simone@dracoon.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
httpx = "^0.23.3"
pydantic = "^1.10.7"
cryptography = "^40.0.1"
tenacity = "^8.2.2"
asyncio = "^3.4.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"